apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgss1
spec:
  selector:
    matchLabels:
      run: pgss1
  serviceName: "pgss1"
  template:
    metadata:
      labels:
        run: pgss1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: hello-postgres
        image: postgres:11.2
        ports:
        - containerPort: 5432
          name: mypostgresport
        volumeMounts:
        - name: postgresdatapath    #match here
          mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
  - metadata:
      name: postgresdatapath   #match here 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: pgss1
  name: pgss1
  namespace: default
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    name: mypostgresport
  selector:
    run: pgss1
  sessionAffinity: None
  type: NodePort
